---
#
# Trivial Passenger memory monitor. By default it is executed from cron every
# five minutes and it kills one process that exceeds the RSS memory threashold
# configured.
#

# Set to 'false' to completely disable this script.
:ENABLED: true

# RSS memory threashold to recycle processes (in kB).
:MAX_PRIV_RSS_MEMORY: 2_000_000

# Kill only one process during to let Passenger to do rolling replacement.
# Setting to false will cause killing ALL processes exceeding
# MAX_PRIV_RSS_MEMORY leading to possible service disruption for some time
# until Passenger spawns the initial worker.
:ONE_ONLY: true

# Kill processes which do not terminate gracefully using SIGKILL after
# GRACEFUL_SHUTDOWN_SLEEP period.
:KILL_BUSY: true

# Amount of seconds to wait for graceful shutdown (SIGTERM) until a process
# kill (SIGKILL) is sent. Must be lower than 5 minutes (300 seconds).
:GRACEFUL_SHUTDOWN_SLEEP: 90

# Print 'passenger-status' and 'ps' output before termination to get some extra
# information via email from cron. Only printed when a kill is performed.
:SEND_STATUS: true

# Print verbose information "Process terminating" or "Process killed".
:VERBOSE: true

# Print extra debugging information.
:DEBUG: false
